
packer {
  required_plugins {
    amazon = {
      source  = "github.com/hashicorp/amazon"
      version = "~> 1"
    }
  }
}

data "amazon-ami" "ubuntu" {
  filters = {
    virtualization-type = "hvm"
    name = "ubuntu/images/*ubuntu-*-20.04-amd64-server-*"
    root-device-type = "ebs"
  }
  owners = ["099720109477"]
  most_recent = true
}

variable "region" {
  type    = string
  default = "eu-west-1"
}

source "amazon-ebs" "builder-ubuntu" {
  ami_block_device_mappings {
    delete_on_termination = true
    device_name           = "/dev/sda1"
    volume_size           = 12
    volume_type           = "gp3"
  }
  ami_description     = "Generated by Packer. Runs an apache server with PHP"
  ami_name            = "web-{{ isotime \"2006-01-02-15-04\" }}"
  enable_t2_unlimited = false
  encrypt_boot        = true
  instance_type       = "m7i.large"
  region              = "eu-west-1"
  run_tags = {
    Name        = "Builder: web server"
    environment = "build"
  }
  source_ami        = data.amazon-ami.ubuntu.id
  ssh_username = "ubuntu"
  tags = {
    Name = "Web server"
  }
}

build {
  sources = ["source.amazon-ebs.builder-ubuntu"]

  provisioner "file" {
    destination = "/tmp/awslogs.conf"
    source      = "./awslogs.conf"
  }

  provisioner "file" {
    destination = "/tmp/aws.config"
    source      = "./aws.config"
  }

  provisioner "shell" {
    script = "./install.sh"
  }

}
