aws_id = "find this: https://console.aws.amazon.com/billing/home?#/account"
aws_region = "eu-west-1"
domain = "phpuk-YOUR-HANDLE.1webservices.co.uk"
zone_id = "Z1FD39K9CKJE4X"
vpc_id = "find this: https://eu-west-1.console.aws.amazon.com/vpc/home?region=eu-west-1#vpcs:sort=VpcId"
s3-load-balancer-logs = "YOUR-HANDLE-phpuk-elb-logs"
s3-deploy = "YOUR-HANDLE-phpuk-deploy"
