aws_id = "find this: https://console.aws.amazon.com/billing/home?#/account"
aws_region = "eu-west-1"
domain = "your.domain.com"
zone_id = "Z1XXXXX"
vpc_id = "find this: https://eu-west-1.console.aws.amazon.com/vpc/home?region=eu-west-1#vpcs:sort=VpcId"
s3-load-balancer-logs = "YOUR-HANDLE-elb-logs"
s3-deploy = "YOUR-HANDLE-deploy"
